### ISSUE TITLE
J26 Breadcrumbs V5.3.1 icons not working

### ISSUE THREAD

**Issue by mparsley13** [j26design/Breadcrumbs#1]
Everything else is working amazingly! Google is properly indexing the breadcrumb path, so no problems there. 

It's just the arrow and home icons no longer work. 

I've already tried to take them out & put them back in across the entire site to no avail. 

Website https://bnbpresents.com

I've also attached a screen shot. 

Please help! 
![breadcrumb screen shot](https://user-images.githubusercontent.com/29955852/27923007-90153010-6242-11e7-8176-0784558d6bde.jpg)

**Comment by jp26jp** [comment]
Make sure you're using the [current stylesheet](https://www.j-26.com/resources/icon-stylesheet/)
