### ISSUE TITLE
Please Help. Images on breadcrumbs not working. 

### ISSUE THREAD

**Issue by acusheetmetal** [j26design/Breadcrumbs#2]
When I preview my site in Muse it works fine. When I exported my html and uploaded, you will see an example here. https://www.acumetalfab.com/draft-beer-drip-trays.html

I see the code in my html for your style sheet that you recommend in the master page. Please help.

**Comment by jp26jp** [comment]
I don't see any breadcrumbs on that page.

**Comment by acusheetmetal** [comment]
That is really concerning if you don't. I have them on every page except my home page. I can't see the home elblem or arrows. I cleared my broswer history. On my computer and my phone I installed chrome beta   and dolphin browser. Still nothing. Now my wife did it at work (I work there part time cause it is a family business I help out with on my days off) and she could see the emblems. So I am not sure what is going on. See the screenshot from my Moto Z Droid Force running latest version of Chrome mobile[
![screenshot_20170712-162557](https://user-images.githubusercontent.com/30088527/28144319-aaa99d8a-671f-11e7-9ab3-49550118fb4a.png)
](url)

This is off that same page I sent you the link. They should be below my header image and my menu. Top left.

**Comment by jp26jp** [comment]
I can see the icons too so try clearing your cache.

**Comment by acusheetmetal** [comment]
That is so weird. I even wiped my cache on my app and still don't see it. I guess I will assume it works but it still concerns me if it maybe something else. Thanks for your time.

**Comment by jp26jp** [comment]
Make sure you have [the correct stylesheet](https://www.j-26.com/resources/icon-stylesheet/) placed in the `<head>` of your master page.
